#pragma once

#include <vector>
#include <string>

enum class SCRIPT_TYPE
{
	BARBEDBLOCKSCRIPT,
	BLOCKSCRIPT,
	BOMBFLOWERSCRIPT,
	BOMBSCRIPT,
	BREAKABLESMALLSTONESCRIPT,
	BREAKABLESTONESCRIPT,
	BTNSCRIPT,
	BUGMONSTERSCRIPT,
	CAMERASCRIPT,
	CHARACTERSELECTSCRIPT,
	CUTSCENESCRIPT,
	DAMAGEFONTSCRIPT,
	DROPMISSILESCRIPT,
	ELECBLOCKSCRIPT,
	ELECCHILDSCRIPT,
	ELECEFFECTSCRIPT,
	ELECTOWERSCRIPT,
	ENDBLOCKSCRIPT,
	FIREBOWLSCRIPT,
	FIREWOODSCRIPT,
	FSMSCRIPT,
	HITEFFECTSCRIPT,
	HITSCRIPT,
	HPHARSCRIPT,
	INVADERSCRIPT,
	JUMPUPSCRIPT,
	MAPSCRIPT,
	MINOTAUROS,
	MISSILESCRIPT,
	MONSTERSCRIPT,
	OBJEVENTSCRIPT,
	OBJSTATE,
	OBJTILECOL,
	PLAYERPOSSETSCRIPT,
	PLAYERSCRIPT,
	POSSETTARGETSCRIPT,
	PUSHSMALLSTONESCRIPT,
	PUSHSTONESCRIPT,
	RADIANDIRSCRIPT,
	REDBUTTONSCRIPT,
	SAPA,
	SOUNDSCRIPT,
	SPEEDUPSCRIPT,
	SPINBULLETSCRIPT,
	STONEDOORSCRIPT,
	TARGETSEARCHSCRIPT,
	TARGETTOAUTO,
	TILECOLLSION,
	TOUCHSCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
